### ISSUE TITLE
fix: clear comment textarea after comment sent

### ISSUE THREAD

**Issue by romankurnovskii** [romankurnovskii/cloud-exam-prepare#14]
expected: clear textarea after user sends comment

**Comment by Aksa12** [comment]
Hey, can I work on this issue?

**Comment by romankurnovskii** [comment]
> Aksa12

Hello and thank you for reply. Just pull request

How to reproduce:
1. Get any random question
2. send comment
3. after comment is send the textarea should be empty
![Screen Shot 2022-10-12 at 18 17 34](https://user-images.githubusercontent.com/59924334/195382219-59c3514b-2f6f-443b-9b1d-3bfbd04ac9ac.png)

**Comment by Aksa12** [comment]
Great, thanks.

**Comment by Aksa12** [comment]
@romankurnovskii Fixed in the PR above

**Comment by romankurnovskii** [comment]
> @romankurnovskii Fixed in the PR above

merged, thank you
